Feature/jo/fdp storage
fairDataSociety/fairdrive-theapp pull request #102
Opened 2022-07-26 12:57 UTC by jayolin

2022-07-28 12:38 UTC, molekilla requested changes

2022-07-28 12:38 UTC, molekilla commented on src/components/Forms/ConfirmMnemonic/ConfirmMnemonic.tsx
> +  //   const mnemonic = localStorage.getItem('registerMnemonic');
remove commented out code

2022-07-28 12:38 UTC, molekilla commented on src/components/Forms/ConfirmMnemonic/ConfirmMnemonic.tsx
> +  //   const mnemonic = localStorage.getItem('registerMnemonic');
or add a comment, I guess is the pending pod integration

2022-07-28 12:38 UTC, molekilla commented on src/components/Forms/LoginForm/LoginForm.tsx
> +    // login(data)
this can be removed

2022-07-28 12:38 UTC, molekilla commented on src/context/FdpStorageContext.tsx
> +  //     contractAddresses: {
this can be cleaned up

2022-07-28 12:38 UTC, molekilla commented on src/pages/_app.tsx
> +//     try {
add a comment on how we use this postage batch helper

2022-07-28 12:38 UTC, molekilla commented on src/pages/register/payment/index.tsx
> +      // await Promise.all([
this is also pending pods api working

2022-07-28 12:38 UTC, molekilla commented on src/pages/register/payment/index.tsx
> +      // const wallet = Wallet.fromMnemonic(mnemonic);
this can be removed

2022-08-10 14:40 UTC, molekilla approved these changes

2022-08-10 14:41 UTC, molekilla commented
@crtahlin please approve and merge

2022-08-11 12:05 UTC, crtahlin commented
I am not technical enough to review code; @tfius please review.

2022-08-15 10:29 UTC, molekilla commented
@tfius let me know, need this code review to continue with the other issues

2022-08-17 14:33 UTC, merged