feat: pod deletion (#279)
fairDataSociety/fairdrive-theapp pull request #464
Opened 2023-08-28 11:43 UTC by tomicvladan

Added buttons for pod deletion.

Closes #279

2023-08-28 11:50 UTC, IgorShadurin requested changes
The delete icon is much larger than the other icons, both on PC and mobile.

<img width="1325" alt="Screenshot 2023-08-28 at 14 47 50" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/57b835a0-805c-4a90-b1d0-1b75c4d04bc4">
<img width="506" alt="Screenshot 2023-08-28 at 14 47 43" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/c7cd3e56-b110-45b2-bf80-93da3660b100">

2023-09-01 08:42 UTC, IgorShadurin approved these changes
UI is ok. But maybe it doesn't need to be merged until the cause is found https://github.com/fairDataSociety/fdp-storage/issues/257

2026-06-16 00:26 UTC, plur9 commented
This PR has been open for over 2 years (since Aug 2023) with no recent activity. Is this still being worked on? If the pod deletion feature (#279) is still on the roadmap, the diff should be rebased on main before review. Please update or close if abandoned.

2026-06-17 05:24 UTC, plur9 commented
**Staleness triage** (PR open since Aug 2023 — 2+ years)

This PR adds pod deletion buttons and has 1 approval from @IgorShadurin. Pod deletion is a useful feature. However, 2+ years of development means this branch has diverged significantly from main and would need a full rebase before merge.

**Recommendation:** If pod deletion is still on the roadmap, this should be rebased onto current main and re-reviewed before merging. If it's no longer a priority, closing and reopening a fresh branch later is cleaner.

@tfius / @tomicvladan — what's the current status? Should this be rebased or closed?

2026-06-19 02:51 UTC, plur9 commented
This PR has been open since August 2023 (nearly 2 years) with no CI checks and no recent activity. Is it still relevant? Please update, rebase against the current development branch, or close if this work has been superseded.

2026-06-20 00:38 UTC, plur9 commented
This PR has been open since August 2023 (2+ years) with no recent commits or reviews. Is it still active? If the pod deletion feature (#279) is still planned, please rebase on master and update — otherwise consider closing so the issue can be picked up fresh.

2026-06-28 00:06 UTC, plur9 commented
This PR has been open since August 2023 (now 3+ years) and was last updated on June 20. Is this still active and targeted at the current fairdrive-theapp codebase? The architecture has evolved significantly since 2023 (fdp-storage absorbed into Fairdrive). Please either update with a rebase and notes on current relevance, or close if no longer applicable.

2026-06-28 07:03 UTC, plur9 commented
Closing as stale — this PR has been open since Aug 2023 (2+ years), is in CONFLICTING state against the development branch, and would need a full rebase to be mergeable. The pod deletion feature (#279) may still be valuable — if so, please open a fresh PR against the current codebase. Closing to keep the PR queue clean.

2026-06-28 07:03 UTC, closed without merging