feat: new file preview
fairDataSociety/fairdrive-theapp pull request #516
Opened 2023-09-19 13:30 UTC by tomicvladan

File preview reimplemented. Now it supports text files as well.

2023-09-19 18:01 UTC, IgorShadurin requested changes
When checking the preview, I came across the fact that when opening previews for .html/.pdf files in the preview window, the files are still downloaded. I believe that downloading can be disabled for unsupported file types.
wdyt?

2023-09-20 08:36 UTC, tomicvladan commented
Good point. I didn't pay attention that files were still being downloaded even if cannot be previewed.

2023-09-20 09:24 UTC, IgorShadurin requested changes
Feels quite responsive now!
There is a suggestion to not show an error for an unsupported file type. An error is something that doesn't go according to plan. However, an unsupported format is normal and the error can be hidden.

(optional) Without error, the distance between the file name and its size can be increased to improve display. But if the distance between the elements is no less than between other elements, then you can leave it that way.

File type that not supported
<img width="477" alt="Screenshot 2023-09-20 at 12 07 50" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/11f8839b-91c4-4064-b1a3-9ce8e7e68cb5">

If hide error message for not supported types
<img width="417" alt="Screenshot 2023-09-20 at 12 12 26" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/bfba075d-32b9-45d2-9b2e-b74f196741f2">

If increase distance between elements
<img width="436" alt="Screenshot 2023-09-20 at 12 14 40" src="https://github.com/fairDataSociety/fairdrive-theapp/assets/1595061/2e0c6b3f-719f-4302-8f00-02a6fcaf541c">

2023-09-20 12:01 UTC, tfius approved these changes

2023-09-20 12:02 UTC, merged