fix: searchbar appearing (#549)
fairDataSociety/fairdrive-theapp pull request #555
Opened 2023-10-20 14:17 UTC by tomicvladan

Changes appearing of searchbar when it becomes active.

Closes #549

2023-10-20 14:17 UTC, tomicvladan commented
@tamas6 Please let me know what you thing about this animation?

2023-10-20 15:13 UTC, tamas6 commented
> @tamas6 Please let me know what you thing about this animation?

Now is descending but I'd prefer to appear after the sync dots disappear, and upwards, but this is my personal taste, What Do You Think  @IgorShadurin

2023-10-20 15:27 UTC, tamas6 requested changes
Now is descending but I'd prefer it to appear after the sync dots disappear, and upwards, but this is my personal taste, What Do You Think @IgorShadurin

2023-10-23 11:41 UTC, tfius approved these changes

2023-10-23 11:41 UTC, merged