fix: list view (#565)
fairDataSociety/fairdrive-theapp pull request #566
Opened 2023-12-08 12:51 UTC by tomicvladan

Drive list view fix #565

2023-12-11 13:17 UTC, IgorShadurin requested changes

2023-12-11 13:17 UTC, IgorShadurin commented on src/components/Views/DriveListView/DriveListView.tsx
> +  const folderStartIndex =
const folderStartIndex = Math.min(page * rowsPerPage, folderLength);

2023-12-11 13:17 UTC, IgorShadurin commented on src/components/Views/DriveListView/DriveListView.tsx
> +  const folderEndIndex =
const folderEndIndex = Math.min(folderStartIndex + rowsPerPage, folderLength);

2023-12-12 16:27 UTC, tamas6 requested changes
tested, for me the list view/grid view worked as expected but the "sort" button did nothing when in list view, only when  in grid . 🧐

2023-12-14 12:52 UTC, tomicvladan commented
I made a fix for sorting, so now it's working, but the component should be fixed later not to mutate state directly.

2023-12-14 18:08 UTC, tfius approved these changes

2023-12-14 18:08 UTC, merged